version: "3.8"
services:
  next:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - /app/node_modules # Previene problemi di permessi tra host e container
    environment:
      - NODE_ENV=development
